"""Pydantic schemas for the SautiRelay backend API contract."""

from .auth import AuthTokenResponse, LoginRequest, UserSummary
from .clusters import ClusterDetail, ClusterListResponse, ClusterStatus, ClusterSummary
from .common import (
    AuditEvent,
    Channel,
    ErrorResponse,
    LocationPrecision,
    LocationVisibility,
    MetricCount,
    ReportCategory,
    RiskLevel,
    StatusResponse,
    Urgency,
    UserRole,
)
from .escalations import (
    EscalationCreateRequest,
    EscalationDetail,
    EscalationListResponse,
    EscalationStatus,
    EscalationSummary,
    OutcomeCreateRequest,
    OutcomeDetail,
    OutcomeType,
)
from .metrics import DashboardMetricsResponse
from .reports import (
    AiIntakeResult,
    ConsentInput,
    ReportCreateRequest,
    ReportCreateResponse,
    ReportDetail,
    ReporterSafeStatus,
    ReportListResponse,
    ReportProcessResponse,
    ReportStatus,
    ReportStatusResponse,
    ReportSummary,
    SafeLocationInput,
    VerificationDecision,
    VerificationRequest,
    VerificationResponse,
)

__all__ = [
    "AiIntakeResult",
    "AuditEvent",
    "AuthTokenResponse",
    "Channel",
    "ClusterDetail",
    "ClusterListResponse",
    "ClusterSummary",
    "ClusterStatus",
    "ConsentInput",
    "DashboardMetricsResponse",
    "ErrorResponse",
    "EscalationCreateRequest",
    "EscalationDetail",
    "EscalationListResponse",
    "EscalationSummary",
    "EscalationStatus",
    "LocationPrecision",
    "LocationVisibility",
    "LoginRequest",
    "MetricCount",
    "OutcomeCreateRequest",
    "OutcomeDetail",
    "OutcomeType",
    "ReportCategory",
    "ReportCreateRequest",
    "ReportCreateResponse",
    "ReportDetail",
    "ReportListResponse",
    "ReportProcessResponse",
    "ReporterSafeStatus",
    "ReportStatus",
    "ReportStatusResponse",
    "ReportSummary",
    "RiskLevel",
    "SafeLocationInput",
    "StatusResponse",
    "Urgency",
    "UserRole",
    "UserSummary",
    "VerificationDecision",
    "VerificationRequest",
    "VerificationResponse",
]
